"""Registry of all supported OAuth providers with setup instructions."""

PROVIDER_REGISTRY = {
    # --- Communication & Email ---
    "google": {
        "display_name": "Google",
        "category": "Productivity",
        "description": "Gmail, Calendar, Drive, Contacts",
        "icon": "G",
        "color": "red",
        "setup_url": "https://console.cloud.google.com/apis/credentials",
        "docs_url": "https://developers.google.com/identity/protocols/oauth2",
        "scopes": [
            "openid", "email", "profile",
            "https://www.googleapis.com/auth/gmail.readonly",
            "https://www.googleapis.com/auth/gmail.send",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/drive.file",
        ],
        "setup_steps": [
            "Go to Google Cloud Console → APIs & Services → Credentials",
            "Click 'Create Project' if you don't have one (name it anything)",
            "Click 'Create Credentials' → 'OAuth client ID'",
            "If prompted, configure the OAuth consent screen first (External, fill in app name and email)",
            "Application type: 'Web application'",
            "Name: 'CloudGentic Gateway'",
            "Under 'Authorized redirect URIs', add: {callback_url}",
            "Click 'Create' and copy the Client ID and Client Secret",
        ],
    },
    "slack": {
        "display_name": "Slack",
        "category": "Communication",
        "description": "Messages, channels, files, reactions",
        "icon": "S",
        "color": "purple",
        "setup_url": "https://api.slack.com/apps",
        "docs_url": "https://api.slack.com/authentication/oauth-v2",
        "scopes": [
            "channels:read", "channels:write", "chat:write",
            "files:read", "files:write", "users:read",
        ],
        "setup_steps": [
            "Go to api.slack.com/apps and click 'Create New App'",
            "Choose 'From scratch', name it 'CloudGentic Gateway'",
            "Select your workspace",
            "Go to 'OAuth & Permissions' in the sidebar",
            "Under 'Redirect URLs', add: {callback_url}",
            "Under 'Scopes' → 'User Token Scopes', add the scopes you need",
            "Go to 'Basic Information' and copy the Client ID and Client Secret",
        ],
    },
    "twitter": {
        "display_name": "Twitter / X",
        "category": "Social Media",
        "description": "Tweets, DMs, follows, timeline",
        "icon": "X",
        "color": "slate",
        "setup_url": "https://developer.x.com/en/portal/projects-and-apps",
        "docs_url": "https://developer.x.com/en/docs/authentication/oauth-2-0",
        "scopes": [
            "tweet.read", "tweet.write", "users.read",
            "dm.read", "dm.write", "follows.read",
        ],
        "setup_steps": [
            "Go to developer.x.com and sign in",
            "Navigate to the Developer Portal → Projects & Apps",
            "Create a new Project and App (or use existing)",
            "Go to your App → Settings → 'User authentication settings' → Set up",
            "App permissions: 'Read and write'",
            "Type of App: 'Web App'",
            "Callback URL: {callback_url}",
            "Website URL: your gateway URL",
            "Copy the Client ID and Client Secret from 'Keys and tokens'",
        ],
    },
    "facebook": {
        "display_name": "Facebook",
        "category": "Social Media",
        "description": "Pages, posts, messages, insights",
        "icon": "f",
        "color": "blue",
        "setup_url": "https://developers.facebook.com/apps/",
        "docs_url": "https://developers.facebook.com/docs/facebook-login/",
        "scopes": [
            "email", "public_profile", "pages_manage_posts",
            "pages_read_engagement", "pages_messaging",
        ],
        "setup_steps": [
            "Go to developers.facebook.com and click 'My Apps' → 'Create App'",
            "Choose app type: 'Business'",
            "Fill in app name: 'CloudGentic Gateway'",
            "In the dashboard, click 'Add Product' → 'Facebook Login' → 'Set Up'",
            "Choose 'Web'",
            "Go to Facebook Login → Settings",
            "Add to 'Valid OAuth Redirect URIs': {callback_url}",
            "Go to Settings → Basic to find your App ID and App Secret",
        ],
    },
    "instagram": {
        "display_name": "Instagram (Meta)",
        "category": "Social Media",
        "description": "Posts, stories, comments, insights",
        "icon": "I",
        "color": "pink",
        "setup_url": "https://developers.facebook.com/apps/",
        "docs_url": "https://developers.facebook.com/docs/instagram-api/",
        "scopes": [
            "instagram_basic", "instagram_content_publish",
            "instagram_manage_comments", "instagram_manage_insights",
        ],
        "setup_steps": [
            "Instagram API uses Facebook's developer platform",
            "Go to developers.facebook.com → 'My Apps' → 'Create App'",
            "Choose app type: 'Business'",
            "In the dashboard, click 'Add Product' → 'Instagram' → 'Set Up'",
            "Go to Instagram → Basic Display → 'Create New App'",
            "Add to 'Valid OAuth Redirect URIs': {callback_url}",
            "Copy the Instagram App ID and Instagram App Secret",
            "Note: You need a Facebook Page linked to an Instagram Business account",
        ],
    },
    "tiktok": {
        "display_name": "TikTok",
        "category": "Social Media",
        "description": "Videos, comments, user info",
        "icon": "T",
        "color": "slate",
        "setup_url": "https://developers.tiktok.com/apps/",
        "docs_url": "https://developers.tiktok.com/doc/oauth-user-access-token-management/",
        "scopes": [
            "user.info.basic", "video.list", "video.upload",
        ],
        "setup_steps": [
            "Go to developers.tiktok.com and log in",
            "Click 'Manage Apps' → 'Create App'",
            "Fill in app details and description",
            "Under 'Platform', add 'Web' with your gateway URL",
            "Add redirect URI: {callback_url}",
            "Add the scopes/products you need (Video Kit, etc.)",
            "Submit for review (TikTok requires app review)",
            "Once approved, find Client Key and Client Secret in app settings",
        ],
    },
    "stripe": {
        "display_name": "Stripe",
        "category": "Payments",
        "description": "Payments, customers, invoices, subscriptions",
        "icon": "S",
        "color": "indigo",
        "setup_url": "https://dashboard.stripe.com/apikeys",
        "docs_url": "https://docs.stripe.com/connect/oauth-reference",
        "scopes": ["read_write"],
        "setup_steps": [
            "Go to dashboard.stripe.com → Developers → API Keys",
            "For OAuth Connect: Go to Settings → Connect → Platform Settings",
            "Enable OAuth for your platform",
            "Add redirect URI: {callback_url}",
            "Copy the Client ID from Connect settings",
            "Copy the Secret Key from API Keys (use the 'Restricted key' for production)",
            "Note: Use 'Test mode' keys for development",
        ],
    },
    "hubspot": {
        "display_name": "HubSpot",
        "category": "CRM",
        "description": "Contacts, deals, tickets, email, marketing",
        "icon": "H",
        "color": "orange",
        "setup_url": "https://developers.hubspot.com/",
        "docs_url": "https://developers.hubspot.com/docs/api/oauth-quickstart-guide",
        "scopes": [
            "crm.objects.contacts.read", "crm.objects.contacts.write",
            "crm.objects.deals.read", "crm.objects.deals.write",
        ],
        "setup_steps": [
            "Go to developers.hubspot.com and log in",
            "Click 'Apps' in the top nav → 'Create App'",
            "Fill in app name: 'CloudGentic Gateway'",
            "Go to the 'Auth' tab",
            "Add redirect URL: {callback_url}",
            "Under 'Scopes', select the scopes your agents need",
            "Copy the Client ID and Client Secret from the 'Auth' tab",
        ],
    },
    "gohighlevel": {
        "display_name": "GoHighLevel",
        "category": "CRM",
        "description": "Contacts, conversations, calendars, opportunities",
        "icon": "G",
        "color": "emerald",
        "setup_url": "https://marketplace.gohighlevel.com/",
        "docs_url": "https://highlevel.stoplight.io/docs/integrations/",
        "scopes": [
            "contacts.readonly", "contacts.write",
            "conversations.readonly", "conversations.write",
            "calendars.readonly",
        ],
        "setup_steps": [
            "Go to marketplace.gohighlevel.com and sign in as a developer",
            "Click 'My Apps' → 'Create App'",
            "Fill in app details",
            "Set the App Type to 'Sub-Account' or 'Agency' based on your needs",
            "Add redirect URI: {callback_url}",
            "Select the scopes/permissions your agents need",
            "Copy the Client ID and Client Secret from your app settings",
        ],
    },
    "salesforce": {
        "display_name": "Salesforce",
        "category": "CRM",
        "description": "Leads, contacts, opportunities, accounts, cases",
        "icon": "SF",
        "color": "cyan",
        "setup_url": "https://login.salesforce.com/",
        "docs_url": "https://help.salesforce.com/s/articleView?id=sf.remoteaccess_authenticate.htm",
        "scopes": ["api", "refresh_token", "full"],
        "setup_steps": [
            "Log in to Salesforce → Setup (gear icon)",
            "Search for 'App Manager' in Quick Find",
            "Click 'New Connected App'",
            "Fill in: App Name ('CloudGentic Gateway'), API Name, Contact Email",
            "Check 'Enable OAuth Settings'",
            "Callback URL: {callback_url}",
            "Select OAuth Scopes: 'Full access (full)' or specific scopes",
            "Click 'Save' (may take 2-10 minutes to activate)",
            "Go to 'Manage Consumer Details' to get Consumer Key (Client ID) and Consumer Secret",
        ],
    },
    "discord": {
        "display_name": "Discord",
        "category": "Communication",
        "description": "Messages, servers, channels, members",
        "icon": "D",
        "color": "indigo",
        "setup_url": "https://discord.com/developers/applications",
        "docs_url": "https://discord.com/developers/docs/topics/oauth2",
        "scopes": [
            "identify", "email", "guilds", "messages.read",
        ],
        "setup_steps": [
            "Go to discord.com/developers/applications",
            "Click 'New Application' and name it 'CloudGentic Gateway'",
            "Go to 'OAuth2' in the sidebar",
            "Add redirect: {callback_url}",
            "Copy the Client ID and Client Secret",
        ],
    },
    "linkedin": {
        "display_name": "LinkedIn",
        "category": "Social Media",
        "description": "Profile, posts, connections, company pages",
        "icon": "in",
        "color": "blue",
        "setup_url": "https://www.linkedin.com/developers/apps",
        "docs_url": "https://learn.microsoft.com/en-us/linkedin/shared/authentication/",
        "scopes": [
            "openid", "profile", "email", "w_member_social",
        ],
        "setup_steps": [
            "Go to linkedin.com/developers/apps and click 'Create App'",
            "Fill in app name, LinkedIn Page (required), and logo",
            "Go to 'Auth' tab",
            "Add redirect URL: {callback_url}",
            "Under 'OAuth 2.0 scopes', request the scopes you need",
            "Copy the Client ID and Client Secret from the 'Auth' tab",
        ],
    },
    "github": {
        "display_name": "GitHub",
        "category": "Developer Tools",
        "description": "Repos, issues, PRs, gists, actions",
        "icon": "GH",
        "color": "slate",
        "setup_url": "https://github.com/settings/developers",
        "docs_url": "https://docs.github.com/en/apps/oauth-apps/building-oauth-apps",
        "scopes": [
            "repo", "user", "read:org",
        ],
        "setup_steps": [
            "Go to github.com → Settings → Developer settings → OAuth Apps",
            "Click 'New OAuth App'",
            "Application name: 'CloudGentic Gateway'",
            "Homepage URL: your gateway URL",
            "Authorization callback URL: {callback_url}",
            "Click 'Register application'",
            "Copy the Client ID, then click 'Generate a new client secret'",
        ],
    },
    "notion": {
        "display_name": "Notion",
        "category": "Productivity",
        "description": "Pages, databases, blocks, search",
        "icon": "N",
        "color": "slate",
        "setup_url": "https://www.notion.so/my-integrations",
        "docs_url": "https://developers.notion.com/docs/authorization",
        "scopes": [],
        "setup_steps": [
            "Go to notion.so/my-integrations",
            "Click 'New integration'",
            "Name: 'CloudGentic Gateway', select your workspace",
            "Set type to 'Public' for OAuth (default is Internal)",
            "Add redirect URI: {callback_url}",
            "Copy the OAuth Client ID and OAuth Client Secret",
            "Note: Users will need to grant page access when connecting",
        ],
    },
    "shopify": {
        "display_name": "Shopify",
        "category": "E-Commerce",
        "description": "Products, orders, customers, inventory",
        "icon": "S",
        "color": "green",
        "setup_url": "https://partners.shopify.com/",
        "docs_url": "https://shopify.dev/docs/apps/auth/oauth",
        "scopes": [
            "read_products", "read_orders", "read_customers",
        ],
        "setup_steps": [
            "Go to partners.shopify.com and log in (create a partner account if needed)",
            "Click 'Apps' → 'Create app'",
            "Choose 'Create app manually'",
            "App name: 'CloudGentic Gateway'",
            "App URL: your gateway URL",
            "Allowed redirection URL: {callback_url}",
            "Go to 'Client credentials' to find your API Key (Client ID) and API Secret Key",
        ],
    },
}
